from .research import (
    PAPER_ANALYZER_INSTRUCTIONS,
    VALIDATION_RESEARCHER_INSTRUCTIONS,
    FACT_CHECKER_INSTRUCTIONS,
)
from .market import (
    MARKET_RESEARCHER_INSTRUCTIONS,
    MARKET_SKEPTIC_INSTRUCTIONS,
)
from .ideation import (
    IDEA_GENERATOR_INSTRUCTIONS,
    STRATEGIC_ADVISOR_INSTRUCTIONS,
    DEVILS_ADVOCATE_INSTRUCTIONS,
    IDEA_ROASTER_TEAM_INSTRUCTIONS,
)
from .product import PRODUCT_ENGINEER_INSTRUCTIONS
from .reporting import (
    REPORT_GENERATOR_INSTRUCTIONS,
    PAPER2SAAS_TEAM_INSTRUCTIONS,
)

__all__ = [
    "PAPER_ANALYZER_INSTRUCTIONS",
    "VALIDATION_RESEARCHER_INSTRUCTIONS",
    "FACT_CHECKER_INSTRUCTIONS",
    "MARKET_RESEARCHER_INSTRUCTIONS",
    "MARKET_SKEPTIC_INSTRUCTIONS",
    "IDEA_GENERATOR_INSTRUCTIONS",
    "STRATEGIC_ADVISOR_INSTRUCTIONS",
    "DEVILS_ADVOCATE_INSTRUCTIONS",
    "IDEA_ROASTER_TEAM_INSTRUCTIONS",
    "PRODUCT_ENGINEER_INSTRUCTIONS",
    "REPORT_GENERATOR_INSTRUCTIONS",
    "PAPER2SAAS_TEAM_INSTRUCTIONS",
]
